spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8097
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
  instance:
    preferIpAddress: true